name = "paramcard"
version = "0.2.3"
license = "MIT"
author = "Takahiro Ueda"
maintainer = "t.ueda.od@juntendo.ac.jp"

[fortran]
implicit-typing = true
implicit-external = true
source-form = "default"

[dev-dependencies]
test-drive.git = "https://github.com/fortran-lang/test-drive"
test-drive.tag = "v0.5.0"
