name: Test

on:
  push:
  pull_request:
  schedule:
    - cron: 0 0 1 * * # monthly

jobs:
  test:
    strategy:
      fail-fast: false
      matrix:
        include:
          - { os: ubuntu-18.04, compiler: gcc, version: 5 }
          - { os: ubuntu-18.04, compiler: gcc, version: 6 }
          - { os: ubuntu-18.04, compiler: gcc, version: 7 }
          - { os: ubuntu-18.04, compiler: gcc, version: 8 }
          - { os: ubuntu-20.04, compiler: gcc, version: 9 }
          - { os: ubuntu-20.04, compiler: gcc, version: 10 }
          - { os: ubuntu-22.04, compiler: gcc, version: 11, build-type: coverage }
          - { os: ubuntu-22.04, compiler: gcc, version: 12 }

    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v3

      - name: Set up Fortran
        uses: awvwgk/setup-fortran@main
        id: setup-fortran
        with:
          compiler: ${{ matrix.compiler }}
          version: ${{ matrix.version }}

      - name: Set up fpm
        uses: fortran-lang/setup-fpm@v5
        with:
          fpm-version: v0.7.0

      - name: Print compiler version
        if: matrix.compiler == 'gcc'
        run:
          gfortran --version

      - name: Run test
        if: matrix.build-type != 'coverage'
        run: fpm test

      - name: Run test (with coverage)
        if: matrix.build-type == 'coverage'
        run: fpm test
        env:
          FPM_FFLAGS: -coverage -g -fcheck=bounds -fcheck=array-temps -fbacktrace

      - name: Run gcov
        if: matrix.build-type == 'coverage'
        run: find . -type f -name '*.gcno' -exec gcov -pb {} +

      - name: Upload coverage report
        if: matrix.build-type == 'coverage'
        uses: codecov/codecov-action@v3
        with:
          fail_ci_if_error: true
